// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtNGeT5pC_UP5B6659-8dELRXXC8t4WQ0',
    appId: '1:936279224615:web:5ee583af56a2645829f902',
    messagingSenderId: '936279224615',
    projectId: 'ecommerce-c69f8',
    authDomain: 'ecommerce-c69f8.firebaseapp.com',
    storageBucket: 'ecommerce-c69f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt5QM6Oh1qMQCU8RxEHQIC5i2Eyh8b6aE',
    appId: '1:936279224615:android:0e32d933630d5c7129f902',
    messagingSenderId: '936279224615',
    projectId: 'ecommerce-c69f8',
    storageBucket: 'ecommerce-c69f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD1TayTE6QfzG17Jmt92bGR4GNKLB4Fxg',
    appId: '1:936279224615:ios:93ef09a7764d6f3e29f902',
    messagingSenderId: '936279224615',
    projectId: 'ecommerce-c69f8',
    storageBucket: 'ecommerce-c69f8.appspot.com',
    iosBundleId: 'com.shokhrukhbek.foodNinja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtNGeT5pC_UP5B6659-8dELRXXC8t4WQ0',
    appId: '1:936279224615:web:4f1c70a2a3911d5829f902',
    messagingSenderId: '936279224615',
    projectId: 'ecommerce-c69f8',
    authDomain: 'ecommerce-c69f8.firebaseapp.com',
    storageBucket: 'ecommerce-c69f8.appspot.com',
  );
}
